### ISSUE TITLE
Logo font incorrect on windows

### ISSUE THREAD

**Issue by funkymonk91** [tonysm/importmap-laravel#1]
`font-family` is set to `Ubuntu` in a few spots in the logo svg :). 
![image](https://user-images.githubusercontent.com/3025966/151015631-65237a3c-9aea-40d0-93b5-22286b59b73c.png)

**Comment by tonysm** [comment]
of course I forgot about that.  😅 

Thanks for pointing it out!

**Comment by tonysm** [comment]
I've converted the text to paths, so the should look the same across all operating systems. @funkymonk91 I would appreciate if you could take a look and tell me if it still looks like that. For now, I'll close it.

Again, thanks for pointing it out! :D

**Comment by funkymonk91** [comment]
@tonysm looks good now!

![image](https://user-images.githubusercontent.com/3025966/151048117-bfc47d05-bc01-407a-9065-5e3636a00e18.png)
