### ISSUE TITLE
wrong module url

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/importmap-laravel#4]
after successful i am getting error 404 not found in console this is because the 
`<x-importmap-tags entrypoint="app" />`
is return all module with URL and location like this 
`http://domain.com/js/C:/xampp/htdocs/Domain/core/resources/js/libs/turbo.js
which  is  suppose to be this 
http://auttransfer.com/core/resources/js/libs/turbo.js

how do i achieve this?
`

**Comment by tonysm** [comment]
I assume that's running locally (because of the XAMPP in the URL). Try setting the `ASSET_URL="http://auttransfer.com/"` in your `.env`.

**Comment by odion-cloud** [comment]
i have added this already ,the only change is that it added another / after the domain name like this
http://domain.com//js/C:/xampp/htdocs/Domain/core/resources/js/libs/turbo.js

**Comment by odion-cloud** [comment]
this seem to be coming from this part of the package 
```
<?php

namespace Tonysm\ImportmapLaravel;

use Illuminate\Support\Facades\File;
use Tonysm\ImportmapLaravel\Facades\Importmap;

class AssetResolver
{
    public function __invoke(string $fileRelativePath)
    {
       
        if (! File::exists($absolutePath = Importmap::getRootPath() . '/resources/' . trim($fileRelativePath, '/'))) {
            return asset($fileRelativePath);
        }

        return asset($fileRelativePath) . '?digest=' . (new FileDigest())($absolutePath);
    }
}
```

**Comment by tonysm** [comment]
Which of those lines specifically?

**Comment by odion-cloud** [comment]
this line the return statement
`return asset($fileRelativePath);`

**Comment by tonysm** [comment]
What is the content of the `$fileRelativePath` there? Can you dd it? Sorry, I'm downloading a windows ISO so I can test this on XAMPP

**Comment by tonysm** [comment]
@odion-cloud can you try version `0.4.1`? There was a fix for this: https://github.com/tonysm/importmap-laravel/releases/tag/0.4.1

Closing it for now, but do let me know if this is still a problem.
