### ISSUE TITLE
importmap:pin doesn't download latest version of @hotwired/turbo

### ISSUE THREAD

**Issue by emaia** [tonysm/importmap-laravel#51]
At this time the latest version of @hotwired/turbo is 8.0.2 (https://registry.npmjs.org/@hotwired/turbo) but pin command download the version 8.0.0-beta.2. Same with `--from=unpkg`

```bash
php artisan importmap:pin @hotwired/turbo
Clearing cached manifest...
Manifest file cleared!
Pinning "@hotwired/turbo" to resources/js/vendor/@hotwired/turbo.js via download from https://ga.jspm.io/npm:@hotwired/turbo@8.0.0-beta.2/dist/turbo.es2017-esm.js

```

Tried `importmap:outdated` but this not update the package.

```bash
$ php artisan importmap:outdated

+-----------------+--------------+--------+
| Package         | Current      | Latest |
+-----------------+--------------+--------+
| @hotwired/turbo | 8.0.0-beta.2 | 8.0.2  |
+-----------------+--------------+--------+

1 outdated package found.
```

I'm using importmap version 2.1.1

**Comment by tonysm** [comment]
@emaia is it from an existing app? If so, do you mind sharing the `importmap.php`? Maybe just the existing turbo mapping line.

I just tried it here, it seems to work now... 🤔

**Comment by emaia** [comment]
Hi @tonysm ! It was a bug with jspm. I tried https://generator.jspm.io/ and it was returning errors when selection any version >= 8.0.0. Same error as related here: https://github.com/jspm/project/issues/330 But now it is ok.
